after-startup-command = [
    'exec-and-forget open -a Ghostty',
    'exec-and-forget open -a Obsidian',
    'exec-and-forget open -a "ChatGPT Atlas"',
]

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE && sketchybar --trigger windows_on_spaces',
]

on-focus-changed = ['exec-and-forget sketchybar --trigger window_focus']
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false
accordion-padding = 100

[gaps]
inner.horizontal = 8
inner.vertical = 8

outer.left = 8
outer.right = 8
outer.top = 8
outer.bottom = 8

[key-mapping]
preset = 'qwerty'

# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

[[on-window-detected]]
if.window-title-regex-substring = 'Picture in Picture'
run = ['layout floating', 'move-node-to-workspace scratch']

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'camera'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'System Settings'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Preview'
run = 'layout floating'

# Ghostty
[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty'
if.workspace = 'infra'
run = 'move-node-to-workspace infra'

[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty'
run = 'move-node-to-workspace code'

[[on-window-detected]]
if.app-id = 'com.openai.atlas'
run = 'move-node-to-workspace web'

[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
run = 'move-node-to-workspace obsidian'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace music'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'secondary'
5 = 'secondary'
6 = 'secondary'
7 = 'main'
8 = 'main'
9 = 'main'

[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-0 = 'workspace web'
alt-1 = 'workspace code'
alt-2 = 'workspace infra'
alt-3 = 'workspace term'
alt-4 = 'workspace chat'
alt-5 = 'workspace devops'
alt-6 = 'workspace music'
alt-7 = 'workspace observability'
alt-8 = 'workspace obsidian'
alt-9 = 'workspace scratch'

alt-s = 'mode service'
alt-r = 'mode resize'
alt-w = 'mode windows'
alt-m = 'mode move'

alt-shift-i = 'exec-and-forget /Users/keveenmenezes/Documents/projects/dotfiles/aerospace/scripts/infra.sh'

[mode.service.binding]
esc = 'mode main'
r = ['reload-config', 'mode main']
t = ['exec-and-forget open -a /Applications/Ghostty.app', 'mode main']
c = ['exec-and-forget open -a "Visual Studio Code"', 'mode main']
o = ['exec-and-forget open -a Obsidian', 'mode main']
a = ['exec-and-forget open -a "ChatGPT Atlas"', 'mode main']
f = ['exec-and-forget open -a Finder', 'mode main']

[mode.resize.binding]
h = 'resize width -50'
l = 'resize width +50'
j = 'resize height +50'
k = 'resize height -50'
enter = 'mode main'
esc = 'mode main'

[mode.windows.binding]
esc = 'mode main'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
f = ['fullscreen', 'mode main']
v = ['layout tiles vertical', 'mode main']
b = ['layout tiles horizontal', 'mode main']
a = ['layout accordion', 'mode main']
space = ['layout floating tiling', 'mode main']

# See: https://nikitabobko.github.io/AeroSpace/commands#move
h = ['move left', 'mode main']
j = ['move down', 'mode main']
k = ['move up', 'mode main']
l = ['move right', 'mode main']

r = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']
tab = ['workspace-back-and-forth', 'mode main']
shift-tab = ['move-workspace-to-monitor --wrap-around next', 'mode main']

[mode.move.binding]
esc = 'mode main'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
d = ['move-node-to-workspace web --focus-follows-window', 'mode main']
g = ['move-node-to-workspace code --focus-follows-window', 'mode main']
m = ['move-node-to-workspace infra --focus-follows-window', 'mode main']
b = ['move-node-to-workspace term --focus-follows-window', 'mode main']
s = ['move-node-to-workspace chat --focus-follows-window', 'mode main']
t = ['move-node-to-workspace devops --focus-follows-window', 'mode main']
n = ['move-node-to-workspace music --focus-follows-window', 'mode main']
c = ['move-node-to-workspace observability --focus-follows-window', 'mode main']
l = ['move-node-to-workspace obsidian --focus-follows-window', 'mode main']
p = ['move-node-to-workspace scratch --focus-follows-window', 'mode main']
